# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b59b14d5e9d879a718e3391d0b6a68e54b9f6e6e31bb08e6d3e2943435f3669ee521e999c25f054ab46c639b40f8bd9443b9a49d52d465db4492e8e04ab6ac

test:
  secret_key_base: 87e5f5814cd3d8fdb640eacdf24c8a7c7cd29f1031350b6a2ee5f961228ce06391ba5c46e073e5628739e9e95fa0ae3c2a9166a8e248a3dd5e0265aa56b912de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
